const List<Map<String, dynamic>> WEATHER_STATUS_CONST = [
  {"code": 200, "description": "Trovoada com chuva leve"},
  {"code": 201, "description": "Trovoada com chuva"},
  {"code": 202, "description": "Trovoada com chuva forte"},
  {"code": 230, "description": "Trovoada com garoa leve"},
  {"code": 231, "description": "Trovoada com garoa"},
  {"code": 232, "description": "Trovoada com garoa forte"},
  {"code": 233, "description": "Trovoada com granizo"},
  {"code": 300, "description": "Garoa leve"},
  {"code": 301, "description": "Garoa"},
  {"code": 302, "description": "Garoa forte"},
  {"code": 500, "description": "Chuva leve"},
  {"code": 501, "description": "Chuva moderada"},
  {"code": 502, "description": "Chuva forte"},
  {"code": 511, "description": "Chuva congelante"},
  {"code": 520, "description": "Aguaceiro leve"},
  {"code": 521, "description": "Aguaceiro"},
  {"code": 522, "description": "Aguaceiro forte"},
  {"code": 600, "description": "Neve leve"},
  {"code": 601, "description": "Neve"},
  {"code": 602, "description": "Neve forte"},
  {"code": 610, "description": "Chuva/neve mista"},
  {"code": 611, "description": "Granizo fino"},
  {"code": 612, "description": "Granizo fino forte"},
  {"code": 621, "description": "Aguaceiro de neve"},
  {"code": 622, "description": "Aguaceiro de neve forte"},
  {"code": 623, "description": "Nevadas dispersas"},
  {"code": 700, "description": "Névoa"},
  {"code": 711, "description": "Fumaça"},
  {"code": 721, "description": "Bruma"},
  {"code": 731, "description": "Areia/poeira"},
  {"code": 741, "description": "Nevoeiro"},
  {"code": 751, "description": "Nevoeiro congelante"},
  {"code": 800, "description": "Céu limpo"},
  {"code": 801, "description": "Poucas nuvens"},
  {"code": 802, "description": "Nuvens dispersas"},
  {"code": 803, "description": "Nuvens quebradas"},
  {"code": 804, "description": "Nublado"},
  {"code": 900, "description": "Precipitação desconhecida"},
];
